#!/bin/bash

echo "🔑 Gemini API Key Setup Helper"
echo "================================"
echo ""
echo "Your old Gemini API key was LEAKED and BLOCKED by Google."
echo "You need to create NEW keys to fix the AI image analysis."
echo ""
echo "📋 Steps to Fix:"
echo ""
echo "1. Open this URL in your browser:"
echo "   https://aistudio.google.com/app/apikey"
echo ""
echo "2. Delete the old leaked key (if still visible)"
echo ""
echo "3. Click 'Create API Key' button 3 times to create 3 new keys"
echo ""
echo "4. Copy each key and paste them when prompted below"
echo ""
echo "================================"
echo ""

# Prompt for keys
read -p "Enter your FIRST new Gemini API key: " KEY1
read -p "Enter your SECOND new Gemini API key: " KEY2
read -p "Enter your THIRD new Gemini API key: " KEY3

echo ""
echo "✅ Keys received! Now updating Railway..."
echo ""
echo "📋 Copy these commands and run them in Railway CLI:"
echo ""
echo "railway variables set GEMINI_API_KEY=\"$KEY1\""
echo "railway variables set GEMINI_API_KEY_2=\"$KEY2\""
echo "railway variables set GEMINI_API_KEY_3=\"$KEY3\""
echo ""
echo "OR manually add them in Railway dashboard:"
echo "1. Go to https://railway.app"
echo "2. Select your backend service"
echo "3. Go to Variables tab"
echo "4. Add/update these variables:"
echo "   GEMINI_API_KEY=$KEY1"
echo "   GEMINI_API_KEY_2=$KEY2"
echo "   GEMINI_API_KEY_3=$KEY3"
echo "5. Click Deploy"
echo ""
echo "✅ After updating Railway, test with:"
echo "   cd backend && node test-gemini-quick.js"
echo ""
