[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['npm install --legacy-peer-deps --loglevel verbose']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'

[variables]
NPM_CONFIG_LOGLEVEL = 'verbose'
SKIP_ENV_VALIDATION = 'true'
