[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
NEXT_PUBLIC_API_URL = "https://thrift-shop-backend-production.up.railway.app/api"
NEXT_PUBLIC_COMPANY_ID = "1"
NEXT_PUBLIC_COMPANY_NAME = "Pearl Box"
