-- ============================================================
--  mery-rose-clothing : products table
--  Paste this into the new project's SQL Editor and click RUN.
--  Images are stored as filenames (text), NOT base64 -> stays free.
-- ============================================================

create table if not exists products (
  id                   bigint generated by default as identity primary key,
  name                 text not null,
  description          text,
  price                numeric(10,2),
  original_price       numeric(10,2),
  images               text,            -- comma-separated image filenames
  brand                text,
  size                 text,
  category             text,
  condition            text,
  color                text,
  in_stock             boolean default true,
  visible              boolean default true,
  material             text,
  measurements         text,
  care_instructions    text,
  tags                 text,
  seller_name          text,
  seller_rating        numeric(3,2),
  seller_location      text,
  views                integer default 0,
  likes                integer default 0,
  company_id           bigint,
  display_order        integer,
  reservation_status   text,
  reserved_by_order_id bigint,
  created_at           timestamptz default now(),
  updated_at           timestamptz default now()
);

-- Helpful indexes
create index if not exists products_visible_idx  on products (visible);
create index if not exists products_category_idx on products (category);
