services:
  - type: web
    name: thrift-shop-admin
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3005
      - key: REACT_APP_API_URL
        value: https://thrift-shop-backend.onrender.com/api
